version: "3.4"
services:
  localstack:
    image: fetchdocker/data-takehome-localstack
    ports:
      - "4566:4566"
  postgres:
    image: fetchdocker/data-takehome-postgres
    ports:
      - "5432:5432"
  awslocal:
    build:
        context: .
        dockerfile: Dockerfile.awslocal
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    # comment the following line to use ssh
    command: bash -c "service ssh start && python3 -u /app/main.py"